### ISSUE TITLE
Play Spotify on mirror itself

### ISSUE THREAD

**Issue by majik655** [skuethe/MMM-Spotify#102]
Hello @bugsounet 

So I have two mirrors.  One (my first one) works excellent and has your spotify on it along with a MILLION other modules...all working great.   On this mirror when I play spotify on my phone... I see the mirror as LibreSpot on devices I can play on .,. which then when selected it plays over my mirror speakers.  GOOD.

So now I am starting a second mirror and besides the normal default modules MMM-Spotify is the only module I have installed.
When I play spotify on my phone , this mirror DOES show what is playing (on my phone)... but I do not see this device in my list of devices on spotify to play to.    This mirror is also a touch screen and the controls are also working but I just do not see it on my list of devices.

What am I doing wrong or have forgotten?

**Comment by bugsounet** [comment]
MMM-Spotify can ONLY show what is listening on a device.
It can't play any music.
if you want this feature install an external program to your RPI

**Comment by majik655** [comment]
> 
> 
> MMM-Spotify can ONLY show what is listening on a device.
> It can't play any music.
> if you want this feature install an external program to your RPI

Well now Im really confused ...since it plays through my first mirror... I must have installed raspotify then is the only thing I can think of...

But at least it means I didn't miss anything on your module which works very well  :)

I remember something about setting up or doing something with the word librespot .. it must be with raspotify then.
Thank you
