### ISSUE TITLE
Black Screen since 1.5.0

### ISSUE THREAD

**Issue by M1dn8** [skuethe/MMM-Spotify#104]
After the last update to 1.5.0 the screen of my MagicMirror shows only a blackscreen.
MagicMirror is starting correct and i can't find issues.
Today i tried 1.5.1. but it's still the same problem.

I // the Spotify module in config.js and MagicMirror shows all modules normaly.

Anyone else have this issue or maybe a solution?! 

Thanks for your great work :)

**Comment by bugsounet** [comment]
i think my new npm library is missing

try this:
```sh
cd ~/MagicMirror/modules/MMM-Spotify
git pull
npm install
```

**Comment by M1dn8** [comment]
wow thank u for your fast answer!!!

npm install fix the blackscreen :)

thank you very much! Awesome module and awesome work
