### ISSUE TITLE
Notifications ...

### ISSUE THREAD

**Issue by jamesvcc** [skuethe/MMM-Spotify#105]
I have MMM-Spotify set up to monitor only one of my speakers (lets say it is called Kitchen).  When Kitchen is selected in Spotify as the output device I can see notifications being raised for start/stop/track change etc. as expected.  However I cannot see a notification raised if I am listening to music on "Kitchen" but then change the target output device to something else (like my local phone or another speaker).

Am I missing something or is it possible to raise a notification if the target is moved away from a monitored device to another unmonitored device?

Does the above make sense?

**Comment by bugsounet** [comment]
what notification ? to another module ?

```js
[Notification][MMM-Spotify] SPOTIFY_UPDATE_SONG_INFO {album: {…}, artists: Array(1), available_markets: Array(79), disc_number: 1, duration_ms: 179760, …}
[Notification][MMM-Spotify] SPOTIFY_UPDATE_PLAYING 
[Notification][MMM-Spotify] SPOTIFY_UPDATE_DEVICE {id: "f6097038414aae97350f0cbf6772333c19277c5a", is_active: true, is_private_session: false, is_restricted: false, name: "Jarvis", …}
```
MMM-Spotify emit some notification for another module
but i see i have not documented it...

I don't know if what do you want @jamesvcc ?

**Comment by jamesvcc** [comment]
Sorry, I am probably not explaining myself properly.  I have a module listening for notifications from MMM-Spotify.  I want to be able to detect from a notification that a Spotify Connect device has been changed from one that is in the "allowDevices" array to one that is NOT in the "allowDevices" array.  Is this possible?

**Comment by bugsounet** [comment]
actually not coded
if device is in the array, it's just ignored

**Comment by skuethe** [comment]
Hey there @jamesvcc

some time has passed and some things where added. If you switch from an allowed device to an not allowed device, a `SPOTIFY_DISCONNECTED` notification should be send.
Please verify with the newest master branch and get back to me :)

**Comment by skuethe** [comment]
If there is something not working out, let me know. I'll close the ticket for now.
