### ISSUE TITLE
Error in authentication

### ISSUE THREAD

**Issue by SuperfrogMe** [skuethe/MMM-Spotify#108]
Hi.

I can't success to use the module for multi accounts.
It's 2 accounts attached to the same familly account.
No problem for the first account token (i also try to swap first and second account, and I also have the same result for the second account).
Here is what I have when i try to accept the module for the second account :
![image](https://user-images.githubusercontent.com/44573979/92311377-c8319380-efb6-11ea-9b1f-481059258f12.png)

Both work separately

**Comment by bugsounet** [comment]
if don't want to work:

do it one by one for creating (use single account config for each and modify token name)
and after add the 2 results (use multi account config)

**Comment by SuperfrogMe** [comment]
Hi.
I try your trick. 
Same result :
Only the first account in the config file work.
Without recreating token, i have just to swap first and second account to make the other (and no longer the first) work.

Do you have an idea ?
Can this come from my network or local config ?

**Comment by a-disease** [comment]
With the authentication issue I had to have a different ports specified for each account through the account config and the Spotify redirect uri. But the second issue just seems to be the default profile, the only way to change between accounts from my understanding is by using a notification. There is more information in #87

**Comment by bugsounet** [comment]
My spotify.config.js:
```
[
  {
      "USERNAME": "premium",
      "CLIENT_ID" : "XXXXID1",
      "CLIENT_SECRET" : "XXXXSECRET1",
      "TOKEN" : "./bugsounet-Premium_token.json"
  },
  {
      "USERNAME": "free",
      "CLIENT_ID" : "XXXXID2",
      "CLIENT_SECRET" : "XXXXSECRET2",
      "TOKEN" : "./bugsounet-Free.json"
  }
]
```

Readme Says: 

- `SPOTIFY_ACCOUNT`: change account. payload is the `USERNAME` defined in your account in `spotify.config.json` file
```
this.sendNotification("SPOTIFY_ACCOUNT", "premium")
```
payload could be the number of the account. attention: for first account, number is `0`
```
this.sendNotification("SPOTIFY_ACCOUNT", 0)
```

I send notification via TelegramBot with `/notification SPOTIFY_ACCOUNT 1`

Tested and works...
Lost time ... 15 min
