### ISSUE TITLE
Spotify logo constantly reloading / flickering on "mini" or "default" style when working with "allowDevices" list

### ISSUE THREAD

**Issue by skuethe** [skuethe/MMM-Spotify#112]
I just started using this modul today, thanks maintaining it, looking really great.
Let me just start by saying that I don't know what has happened between @bugsounet and @MichMich but trying to pull other people into your private issues is not the way to go. So I will open this issue here anyways and not in the mm² repo.
As it seems to me, you do want to keep building and improving this module, right?

So after that bumpy start, lets come back to what matters :) 
I have a problem when using this module with a provided `allowDevices` object. If this list is provided with, f.e. one entry and I am listening on another device, the Spotify logo keeps on reloading / flickering.

After some quick looking I would assume it is because of the following (but this is just a quick guess - I am by far no node expert :) ).

- When receiving a `CURRENT_NOPLAYBACK` notification you call `updatePlayback(false)`, which will, eventually, add the `inactive` class on the SPOTIFY DIV and the hole module is hiding
https://github.com/bugsounet/MMM-Spotify/blob/b927eaeb36451789f347ad75a195c10768a082b2/MMM-Spotify.js#L152
- But if we receive a `CURRENT_PLAYBACK` notification and the current playback device is NOT in the `allowDevices` list, it will just reload the dom
https://github.com/bugsounet/MMM-Spotify/blob/b927eaeb36451789f347ad75a195c10768a082b2/MMM-Spotify.js#L121-L122
- On `getDom` function you then just add the `fade-in` class (each second - default `updateInterval` value). There is no handling of the `inactive` class for when using "mini" or "default" style

Would be nice if somebody could have a look at it. I am currently unsure at which point to add some logic for this to stop :)

Thanks!

**Comment by bugsounet** [comment]
sorry for late response... i have so many work actually, i will inspect

in all case that's to report :)

**Comment by skuethe** [comment]
I fixed that in a fork where I also added / fixed other things, but sure, feel free to still look at it if you want

**Comment by bugsounet** [comment]
humm... i see something and i don't like... so make your own...

**Comment by skuethe** [comment]
That's what I thought after seeing you trying to add a "vendor lock" option to this module after inheriting it.

**Comment by skuethe** [comment]
[really?](https://github.com/MichMich/MagicMirror/wiki/3rd-Party-Modules/_compare/f5e1017e67127044ae4b4bd9115bb95d6ec98cf5) getting childish?

**Comment by bugsounet** [comment]
sure

**Comment by bugsounet** [comment]
if you want this module
i will transfert to you, it's more simple !

I will do it

**Comment by bugsounet** [comment]
skuethe/MMM-Spotify already exists

remame it !

**Comment by bugsounet** [comment]
@skuethe : this is no joke ... rename it, i will transfer.
I have no time for this module, (and i don't use it)

**Comment by skuethe** [comment]
So you slept over it and still want to get rid of it seems (after seeing your redirect script commit). Don't really know why you then took it in the first place, but sure go ahead, I renamed the repo

**Comment by bugsounet** [comment]
Hi, i can't transfert it, because you have a fork. (you need to delete it)

I have merge your job (from your master) in skuethe branch of this repo

When deleted tell me for transfert

@bugsounet

**Comment by skuethe** [comment]
done @bugsounet

**Comment by bugsounet** [comment]
Done: Repository transfer to skuethe requested

**Comment by skuethe** [comment]
Thanks, I guess

**Comment by bugsounet** [comment]
perfect Good coding to you ! ;)

If you want source of npm spotify library just tell me ;)
