### ISSUE TITLE
Error in MM log

### ISSUE THREAD

**Issue by bolish** [skuethe/MMM-Spotify#12]
Hi,

I just wanted to report an error I'm facing regarding MMM-Spotify into the MM log, please see below 

> 0|mm  | [SPOTIFY] API Request fail on : /v1/me/player
0|mm  | { Error: socket hang up
0|mm  |     at createHangUpError (_http_client.js:331:15)
0|mm  |     at TLSSocket.socketOnEnd (_http_client.js:423:23)
0|mm  |     at emitNone (events.js:111:20)
0|mm  |     at TLSSocket.emit (events.js:208:7)
0|mm  |     at endReadableNT (_stream_readable.js:1056:12)
0|mm  |     at _combinedTickCallback (internal/process/next_tick.js:138:11)
0|mm  |     at process._tickCallback (internal/process/next_tick.js:180:9) code: 'ECONNRESET' } undefined
0|mm  | Whoops! There was an uncaught exception...
0|mm  | TypeError: Cannot read property 'statusCode' of undefined
0|mm  |     at Request.request [as _callback] (/home/pi/MagicMirror/modules/MMM-Spotify/Spotify.js:189:23)
0|mm  |     at self.callback (/home/pi/MagicMirror/node_modules/request/request.js:185:22)
0|mm  |     at emitOne (events.js:116:13)
0|mm  |     at Request.emit (events.js:211:7)
0|mm  |     at Request.onRequestError (/home/pi/MagicMirror/node_modules/request/request.js:877:8)
0|mm  |     at emitOne (events.js:116:13)
0|mm  |     at ClientRequest.emit (events.js:211:7)
0|mm  |     at TLSSocket.socketOnEnd (_http_client.js:423:9)
0|mm  |     at emitNone (events.js:111:20)
0|mm  |     at TLSSocket.emit (events.js:208:7)
0|mm  | MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?

I don't know yet what the impact is. It's seems still to work well despite the errors.
I was thinking that the error is triggered when MMM-Spotify doesn't find any opened instances (on any device) but that seems weird as I've Raspotidy installed which should be considered as opened anytime.

Hope you will be able to identify what's wrong there.

**Comment by eouia** [comment]
Thanks for your reporting.
This error might occur by too many connections or too slow connection (Not only this module, but also whole entire system)
Or Internet status also be considered.
Not finding device instance is not the reason, rather it would be the result of this error.
For the test; set your `updateInterval` to `2000`. It might help.
Later I'll add error exception for this kind. Thanks again.

**Comment by bolish** [comment]
OK thx, I'm currently testing the updateinterval change. Keep you posted

**Comment by Ejay-3D** [comment]
I got this error when I haven't play a song on any device for a while like devices not initialized. 
For Raspotify it can occur when a song as never been plyed on it ( eg after a reboot ) 
I've experience this error as well but only once.

**Comment by bolish** [comment]
Hi,
I adjusted the intervaltime. It seems I don't get this error on a regular basis anymore but I still get it just after MM launch.
I also have the feeling that it's when no device is initialized as each time I start MM, I get the spotify logo instead of the latest played song. Which is not normal as I'm using raspotify.

**Comment by eouia** [comment]
I'll look inside and update a patch for when abnormal result of getting devices occurs. Plz wait a while.

**Comment by bolish** [comment]
OK thx. The rest of the module is really great already!

**Comment by eouia** [comment]
Hmmm.. weird.
After looking inside, I found that no device is found is not the reason of this error. This error means just internet connection problem(the connection is hung).
And, when none of device is not ready at running moment, it is normal not to show any last song information.
So I just want to know this; when that error occured, Module or Mirror had stopped or been crashed? Or, errors happened but working normally?

**Comment by Ejay-3D** [comment]
Works normaly. Just need to activate a device and it s good

**Comment by bolish** [comment]
Same for me : Works normaly. Just need to activate a device and it s good

**Comment by eouia** [comment]
Ok. I cannot find a way to activate inactive device with the API. It means, it needs to be done by manual. And I guess the reason of error on start might be related with API rate limitation. 
On start, there would several API requests for auth and token refreshing. So the first playback request might be out of rate limit. Regardless there be no official rate limit information, The fact that the shorter `updateInterval` could make this kind of error too, might prove this guessing.
Fortunately, This kind error seems not to be severe problem. So, I'll leave this for a while unless find a better solution.

**Comment by bastos5** [comment]
Hello Eouia,

I have also the same problem. Did you find a solution ?

i got this error :

[SPOTIFY] API Request fail on : /v1/me/player
Error : Client network socket disconnected before secur TLS connection was established.

after that, the MM turns black, and i only see mouse cursor.
if i remove MMM-Spotify i dont have this problem

Bastien

**Comment by eouia** [comment]
@bastos5 
It's not the same problem, you've got different error message.
Which version of node are you using? and which OS and device? There could be TLS 1.0 issue on some environments but not guaranteed. and for that TLS 1.0 issue, I can't fix it.

**Comment by bastos5** [comment]
Hello Thanks for the answer. I will Check tonight, but do you know how can i find the node and TLS version ? Also, its strange because this problem appears 5/10mins after i start the mirror. Before, the mirror works perfectly. Could be a internet issue also ?

**Comment by bastos5** [comment]
![image](https://user-images.githubusercontent.com/50521874/74725554-55d9ab80-523e-11ea-8269-2b6ac391cbed.png)

More information about the error

**Comment by bastos5** [comment]
![IMG_20200216_161001](https://user-images.githubusercontent.com/50521874/74725789-abae5380-523e-11ea-8255-d2e6e34b9903.jpg)

**Comment by eouia** [comment]
Check these;
1) To know node version.
```
node -v
```

2) Confirm You be a PREMIUM member of Spotify

3) Confirm In your Spotify Dev account(https://developer.spotify.com), Your app exists.

4) Confirm In that app setting, `redirect uri` is set as  http://localhost:8888/callback

5) open `spotify.config.json` in MMM-Spotify directory, then confirm your `CLIENT_ID` and `CLIENT_SECRET` set properly.

6) (If exists, remove `token.json`) execute `node first_auth.js` in MMM-Spotify directory. Let's see what happens.

**Comment by bastos5** [comment]
Hello thanks for your answer

1 :  V10.15.3
2 : I have a premium account
3 : my app exist
4 : I confirm
5 : I confirm
6: same..

My spotify module works perfectly until i got this error. its like 5/10min after i power the mirror. 

Bastien

**Comment by bastos5** [comment]
maybe a power save management for the wifi ? i dont know ... its so strange :(

**Comment by eouia** [comment]
ah! possible reason!

**Comment by bastos5** [comment]
Didnt work :(. 
I also switch wifi to 5ghz and itt didnt work aswell
Im running out of option ..
Do you have an idea ?

**Comment by bastos5** [comment]
maybe the problem come from the rate limitation of the API

**Comment by eouia** [comment]
try "updateInterval" to 3000, it will make module dull but can reduce api queries

**Comment by bastos5** [comment]
Already tested ans et didnt work neither

**Comment by eouia** [comment]
Sorry, can't help. I have no idea  any more.

**Comment by bastos5** [comment]
No problem thanks for the Help. I even tried with other spotify module, and i got the same error
