### ISSUE TITLE
Contrôles

### ISSUE THREAD

**Issue by jeff44850** [skuethe/MMM-Spotify#123]
Bonjour et merci d'effectuer le suivi de ce module
J'apprécie énormément les nouvelles fonctionnalités de changement d'appareil et de compte.
J'ai également vu que l'on pouvais contrôler le volume en tactile mais je ne sais pas où le faire 🙄
Faut-il un module spécial ?
Les autres boutons fonctionnent très bien en tactile
Merci encore

**Comment by skuethe** [comment]
Hi there. Please open issues in English. Thanks

**Comment by jeff44850** [comment]
Hello and thank you follow the tracking module of this
I really like the new device and account switching features.
I also saw that we could control the volume by touch but I do not know where to do it🙄
Do you need a special module?
The other buttons work very well in touch
thanks again

**Comment by skuethe** [comment]
Thank you for the feedback and translation :)
I use [MMM-Touch](https://github.com/gfischershaw/MMM-Touch) for all touch related operations. It is very powerful.

An example configuration could be:
```js
    {
      // Have this at the bottom, or else it will "push" down other modules comming after it, even tho it is "hidden"
      module: "MMM-Touch",
      position: "top_right",
      config: {
        useDisplay: false,
        defaultMode: "normalOperation",
        gestureCommands: {
          "normalOperation": {
            // Spotify - increase volume
            "MOVE_UP_1": (commander, gesture) => {
              commander.sendNotification("SPOTIFY_VOLUME_UP")
            },
            // Spotify - decrease volume
            "MOVE_DOWN_1": (commander, gesture) => {
              commander.sendNotification("SPOTIFY_VOLUME_DOWN")
            },
          },
        }
      }
    },
```

The `MOVE_*` command from `MMM-Touch` is described [here](https://github.com/gfischershaw/MMM-Touch/wiki/Manual#swipe-and-move)

**Comment by jeff44850** [comment]
thank you so much
I will study this module 😉

**Comment by skuethe** [comment]
Sure thing. Get back to me if you have any other questions.
