### ISSUE TITLE
Increase the size of buttons

### ISSUE THREAD

**Issue by Ryancru2309** [skuethe/MMM-Spotify#129]
Hello, just wondering if it is possible to increase the size of the play button etc? Any help would be much appriciated. 

Thank you,

**Comment by skuethe** [comment]
Only indirect, as we want to keep aspect ratio of the buttons.
You can modify the following config: `moduleWidth` (default set to: `360`). If you increase the width of the module (assuming you have enough space on the screen), then the buttons will also grow.
In addition, the fewer buttons which are being displayed, the more space they have. So you could set `showAccountButton` and / or `showDeviceButton` to `false`.

If this is all not helping the last option would be to set `style` option to `mini`, which enables the "mini" or rather "compact" display mode. This in addition with `moduleWidth` option can squeeze out some.

**Comment by Ryancru2309** [comment]
No problem. I'll have a play around with it. Thank you
