### ISSUE TITLE
first_auth.js not working

### ISSUE THREAD

**Issue by icripps** [skuethe/MMM-Spotify#13]
hey, i get the following error when i run node first_auth.js
![Screenshot (94)](https://user-images.githubusercontent.com/35995040/55283080-9b407200-5328-11e9-8e98-4ad705d3651f.png)

**Comment by eouia** [comment]
Your port 8888 is used already(by other program? Whatever)
Use other port like 8889.

**Comment by icripps** [comment]
but nothing really is using that port. how do i check if a program is using that  port?

**Comment by eouia** [comment]
I’m not the xnix guru, but google show this as search result first
https://www.google.com/amp/s/www.cyberciti.biz/faq/unix-linux-check-if-port-is-in-use-command/amp/

**Comment by Ejay-3D** [comment]
@icripps Could you please screen shot your URL callback setup on spotify ? 

Then please do a netstat -A | grep 8888

If nothing comes up that mean the port is not in use. 

I think it is related to your URL callback setup on spotify as the adress look strange to me in your screen shot: " ::::8888"  
Should be something like : http://localhost:8888

**Comment by icripps** [comment]
its fine, i just changed the port to 8889 like @eouia said and its working

**Comment by eouia** [comment]
Nice to hear it. I'll close this issue. Have a nice day.
