### ISSUE TITLE
How to do after get clint id in config 

### ISSUE THREAD

**Issue by CherryChethan** [skuethe/MMM-Spotify#130]
hello, I need help and instruction from you hear am already create all the thing in dev Spotify I get the client id and some code also the thing is I didn't get what you explain in the config file setup 3 can you please what should I put in the config file

**Comment by skuethe** [comment]
Hello. Everything you need to know is described in the README. Please read carefully and follow each step.

If you still need help, you have to provide more information from your config / your setup, otherwise I can not help you.

**Comment by skuethe** [comment]
I'll close this for now. As mentioned: come back if you have more information and need more help.
