### ISSUE TITLE
MM crashing with onstart Code

### ISSUE THREAD

**Issue by badshah424** [skuethe/MMM-Spotify#131]
```js
 onStart: {
    deviceName: "RASPOTIFY", //if null, current(last) activated device will be.
    spotifyUri: "spotify:track:3ENXjRhFPkH8YSH3qBXTfQ"
    //when search is set, sportifyUri will be ignored.
    search: {
      type: "playlist", // `artist`, track`, `album`, `playlist` and its combination(`artist,playlist,album`) be available
      keyword: "death metal",
      random:true,
    }
  }
```

I copied and did everything as said.
I copied the above Onstart code in config.j(if this where it has to be)
But when I am trying run magic mirror its crashing .
The error is in above code as when i remove it its working fine but spotify just shows up and gets invisible.
Can you please tell me where I am getting wrong ,If I have pasted the code in right place or is there anything else that need to be done.

**Comment by skuethe** [comment]
> when i remove it its working fine but spotify just shows up and gets invisible

This is the default behavior when you are currently not playing anything and NOT using the `onStart` option.


If you blindly copy and paste the code, chances are it will not work for you setup. If you look closely to the following entry: `deviceName: "RASPOTIFY"`
This is the Spotify device name you want to start listening on. As you copy & pasted, I highly doubt that you have a device with the exact same name in you Spotify device list.

**Comment by badshah424** [comment]
> > when i remove it its working fine but spotify just shows up and gets invisible
> 
> 
> 
> This is the default behavior when you are currently not playing anything and NOT using the `onStart` option.
> 
> 
> 
> 
> 
> If you blindly copy and paste the code, chances are it will not work for you setup. If you look closely to the following entry: `deviceName: "RASPOTIFY"`
> 
> This is the Spotify device name you want to start listening on. As you copy & pasted, I highly doubt that you have a device with the exact same name in you Spotify device list.

I want that the Spotify should play on the USB speakers that I have connected to the Magic Mirror .I don't have a device with Raspotify .

**Comment by badshah424** [comment]
When I put in the code for OnStart magic mirror is encountering error.

**Comment by skuethe** [comment]
> 
> I want that the Spotify should play on the USB speakers that I have connected to the Magic Mirror . I don't have a device with Raspotify .

MMM-Spotify is not a full blown Spotify client. Try adding a device name that exists in your Spotify environment.

**Comment by skuethe** [comment]
I'll close this issue for now. If you have any more trouble getting this to work with an existing spotify device, just open another issue or reply here.
