### ISSUE TITLE
Update notification will not go away above Spotify module

### ISSUE THREAD

**Issue by WeekendDadd** [skuethe/MMM-Spotify#138]
I tried updating the module and still cannot get the “update available for MMM-Spotify module” above the module to go away. Am I doing something wrong?

**Comment by skuethe** [comment]
Hi there. Well what was the outcome of the update command? maybe it failed? do you have local modifications made to the module (except for the account config file ofc)?

**Comment by WeekendDadd** [comment]
I figured it out it was just a merge issue, updated fine now.
