### ISSUE TITLE
Multi-account verification

### ISSUE THREAD

**Issue by crisvdn** [skuethe/MMM-Spotify#144]
I've followed the steps and filled in both CLIENT_ID and CLIENT_SECRET of my partner (as number 1) and me (as number 2) in spotify.config.json (copied the spotify.config.json.example-multi).

After running the command ```node first_auth.js``` it correctly creates username_token.js.
Then it starts up the browser again, but it keeps on throwing "SPOTIFY: Error in authentication" when wanting to accept the spotify request in the browser for the second user.

When I rerun the ```node first_auth.js``` it immediately works and creates another_token.json.

You can test this by removing the username_token and another_token JSON files and running the first_auth.js.

**Comment by skuethe** [comment]
Thank you for opening this issue.

Just to be clear: you currently have multi account up and running with the workaround you described ("just rerun the `node first_auth.js`"), right?

I actually have the multi account setup on my "todo" list and have not yet come around to perform it for myself.
I will see that I find some time to have a look at / fix this.

**Comment by crisvdn** [comment]
Yes its working now. I had to interrupt the first_auth.js with CTRL - C in cmd, then rerun and it will automatically grab the ```another_token```

**Comment by skuethe** [comment]
I have done some major rework on the multi account authentication workflow and tested it successfully on my own setup.
Changes are available in [version `2.0.1`](https://github.com/skuethe/MMM-Spotify/releases/tag/v2.0.1)
