### ISSUE TITLE
INVALID_CLIENT error while using first_auth.js

### ISSUE THREAD

**Issue by Ge-lx** [skuethe/MMM-Spotify#156]
Was fixed by adding the redirect uri `http://localhost:8888/callback` in the spotify developer portal for the app. This should probably be mentioned in the installation guide :)

**Comment by skuethe** [comment]
You should probably read the installation guide first, then you will notice that it is mentioned there ;)

**Comment by Ge-lx** [comment]
My apologies, must have missed that :)
