### ISSUE TITLE
I can't see the module

### ISSUE THREAD

**Issue by F17MC** [skuethe/MMM-Spotify#16]
I installed this module in my MM but I can't see the module. 
I have installed Raspotify and it works fine. I can listen to music with my raspberry, but I can't control the music with assistant mk2, and I can't see the music info. 

My config is:

> {
				module: "MMM-AssistantMk2",
				position: "bottom_right",
				config: {
					useWelcomeMessage: "Bienvenido Fran",
					notifications: {
							ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
							ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
					},
					deviceLocation: {
							coordinates: { 
									latitude:   40.4893538,
									longitude: -3.6827461 
							},
					},
					onIdle: {
						timer: 0, // ESTABA PUESTO CADA 30min (1000*60*30) if you don't want to use this feature, just set timer as `0` or command as ""
						command: ""
					},
					onActivate: {
						timer: 0,
						command: ""
					},
					defaultProfile: "default", 
					profiles: {
							"default" : { // profile name.
									profileFile: "default.json", // profile file name.
									lang: "es-ES"
							},
					},
					record: { // Full values are in `FOR EXPERTS` section.
							recordProgram: "arecord",  // Defaults to "arecord" - also supports "rec" and "sox"
							device: "plughw:1"        // recording device (e.g.: "plughw:1")
					},
					play: { // Full values are in `FOR EXPERTS` section.
							playProgram: "mpg321", // recommended.
					},
					responseVoice: true,
					command: {
						"HIDEMAIL": {
							moduleExec: {
								module:["MMM-Mail"],
								exec: (module, params, key) => {module.hide(1000, {"force":true})}
							}			
						},
						"SHOWMAIL": {
							moduleExec: {
								module:["MMM-Mail"],
								exec: (module, params, key) => {module.show(1000, {"force":true}, {lockString:"AMK2"})}
							}
						},
						"HIDEFEED": {
							moduleExec: {
								module:(params, key)=>{return ["newsfeed"]},
								exec: (module, params, key) => {module.hide(1000, {"force":true})}
							}			
						},
						"SHOWFEED": {
							moduleExec: {
								module:["newsfeed"],
								exec: (module, params, key) => {module.show(1000, {"force":true}, {lockString:"AMK2"})}
							}
						},
						"HIDECAL": {
							moduleExec: {
								module:(params, key)=>{return ["calendar", "calendar_monthly"]},
								exec: (module, params, key) => {module.hide(1000, {"force":true})}
							}			
						},
						"SHOWCAL": {
							moduleExec: {
								module:["calendar", "calendar_monthly"],
								exec: (module, params, key) => {module.show(1000, {"force":true}, {lockString:"AMK2"})}
							}
						},
						"HIDENOTIFICATION": {
							moduleExec: {
								module:(params, key)=>{return ["MMM-PushBulletNotifications"]},
								exec: (module, params, key) => {module.hide(1000, {"force":true})}
							}			
						},
						"SHOWNOTIFICATION": {
							moduleExec: {
								module:["MMM-PushBulletNotifications"],
								exec: (module, params, key) => {module.show(1000, {"force":true}, {lockString:"AMK2"})}
							}
						},
						"HIDEBULLER": {
							moduleExec: {
								module:(params, key)=>{return ["MMM-Buller"]},
								exec: (module, params, key) => {module.hide(1000, {"force":true})}
							}			
						},
						"SHOWBULLER": {
							moduleExec: {
								module:["MMM-Buller"],
								exec: (module, params, key) => {module.show(1000, {"force":true}, {lockString:"AMK2"})}
							}
						},
						"HIDETWEETS": {
							moduleExec: {
								module:(params, key)=>{return ["MMM-TweetsByTimelineOrList"]},
								exec: (module, params, key) => {module.hide(1000, {"force":true})}
							}			
						},
						"SHOWTWEETS": {
							moduleExec: {
								module:["MMM-TweetsByTimelineOrList"],
								exec: (module, params, key) => {module.show(1000, {"force":true}, {lockString:"AMK2"})}
							}
						},
						"HIDEMAPS": {
							moduleExec: {
								module:(params, key)=>{return ["MMM-google-route"]},
								exec: (module, params, key) => {module.hide(1000, {"force":true})}
							}			
						},
						"SHOWMAPS": {
							moduleExec: {
								module:["MMM-google-route"],
								exec: (module, params, key) => {module.show(1000, {"force":true}, {lockString:"AMK2"})}
							}
						},
						"SELFIE": {
							shellExec: {
							exec: "/home/pi/MagicMirror/modules/MMM-AssistantMk2/scripts/selfie.sh",
							options: null,
							}
						},
						"PHOTOTW": {
							shellExec: {
							exec: "python /home/pi/MagicMirror/modules/MMM-AssistantMk2/scripts/Selfie/FotoTwitter.py",
							options: null,
							}
						},
						"APAGA": {
							shellExec: {
							exec: "/home/pi/MagicMirror/modules/MMM-AssistantMk2/scripts/screenoff.sh",
							options: null,
							}
						},
						"ENCIENDE": {
							shellExec: {
							exec: "/home/pi/MagicMirror/modules/MMM-AssistantMk2/scripts/screenon.sh",
							options: null,
							}
						},	
						SPOTIFY_TRANSFER: {
							notificationExec: {
								notification: "SPOTIFY_TRANSFER",
								payload: (params) => {
									console.log("SPOTIFY_TRANSFER @",params)
									return params[1];
								}
							}
						},
						SPOTIFY_PAUSE: {
							notificationExec: {
								notification: "SPOTIFY_PAUSE"
							}
						},
						SPOTIFY_PLAY: {
							notificationExec: {
								notification: "SPOTIFY_PLAY"
							}
						},
						SPOTIFY_MA_PLAYLIST: {
							notificationExec:  {
								notification: "SPOTIFY_PLAY",
								payload: (params) => {
									console.log("SPOTIFY_MA_PLAYLIST")
									return {
										context_uri:"spotify:playlist:0bdByehKVfdsfdsfdsOhF5t",   // Uri of a personnal playlist or album
									}
								},
								notification: "SPOTIFY_SHUFFLE",  // added this to toogle shuffle
								notification: "SPOTIFY_NEXT" // added this to not always have the same song starting first 
							}
						},		
						SPOTIFY_NEXT: {
							notificationExec: {
								notification: "SPOTIFY_NEXT"
							}
						},
						SPOTIFY_PREVIOUS: {
							notificationExec: {
								notification: "SPOTIFY_PREVIOUS"
							}
						},
						SPOTIFY_VOLUME: {
							notificationExec: {
								notification: "SPOTIFY_VOLUME",
								payload: (params) => {
									console.log("SPOTIFY_VOLUME @",params)
									return params[1];
								}
							}
						},
						SPOTIFY_SEARCH: {
							notificationExec: {
								notification: "SPOTIFY_SEARCH",
								payload: (params) => {
									console.log("SPOTIFY_SEARCH @",params)
									return {
										type: "artist,track,album,playlist",
										query: params[1],
										random:false,
									}
								}
							}
						},
						SPOTIFY_SEARCH_PLAYLIST: {
							notificationExec: {
								notification: "SPOTIFY_SEARCH",
								payload: (params) => {
									console.log("SPOTIFY_SEARCH_PLAYLIST @",params)
									return {
										type: "playlist",
										query: params[1],
										random:true,
									}
								}
							}
						},
						CMD_VOLUME_UP: {
							notificationExec: {
								notification: "VOLUME_UP"
							}
						},
						CMD_VOLUME_DOWN: {
							notificationExec: {
							notification: "VOLUME_DOWN"
							}
						},
						CMD_VOLUME_SET: {
							notificationExec: {
								notification: "VOLUME_SET",
								payload: (params, key) => {
									console.log("@", params);
									return params[1];
								}
							}
						}				
					},
					transcriptionHook: {
							"HIDEMAIL": {
								pattern: "oculta mi correo",  // When you say "hide all",
								command: "HIDEMAIL" // command "HIDEMODULES" will be executed
							},
							"SHOWMAIL": {
								pattern: "muestra mi correo",  // When you say "hide all",
								command: "SHOWMAIL" // command "HIDEMODULES" will be executed
							},
							"HIDECAL": {
								pattern: "oculta el calendario",  // When you say "hide all",
								command: "HIDECAL" // command "HIDEMODULES" will be executed
							},
							"SHOWCAL": {
								pattern: "muestra el calendario",  // When you say "hide all",
								command: "SHOWCAL" // command "HIDEMODULES" will be executed
							},
							"HIDEFEED": {
								pattern: "oculta las noticias",  // When you say "hide all",
								command: "HIDEFEED" // command "HIDEMODULES" will be executed
							},
							"SHOWFEED": {
								pattern: "muestra las noticias",  // When you say "hide all",
								command: "SHOWFEED" // command "HIDEMODULES" will be executed
							},
							"HIDENOTIFICATION": {
								pattern: "oculta mis notificaciones",  // When you say "hide all",
								command: "HIDENOTIFICATION" // command "HIDEMODULES" will be executed
							},
							"SHOWNOTIFICATION": {
								pattern: "tengo algo en el móvil",  // When you say "hide all",
								command: "SHOWNOTIFICATION" // command "HIDEMODULES" will be executed
							},
							"HIDEBULLER": {
								pattern: "oculta mi lista de tareas",  // When you say "hide all",
								command: "HIDEBULLER" // command "HIDEMODULES" will be executed
							},
							"SHOWBULLER": {
								pattern: "muestra mi lista de tareas",  // When you say "hide all",
								command: "SHOWBULLER" // command "HIDEMODULES" will be executed
							},
							"HIDETWEETS": {
								pattern: "oculta twitter",  // When you say "hide all",
								command: "HIDETWEETS" // command "HIDEMODULES" will be executed
							},
							"SHOWTWEETS": {
								pattern: "muestra twitter",  // When you say "hide all",
								command: "SHOWTWEETS" // command "HIDEMODULES" will be executed
							},
							"SELFIE": {
								pattern: "selfie",  // When you say "hide all",
								command: "SELFIE" // command "HIDEMODULES" will be executed
							},
							"PHOTOTW": {
								pattern: "sube la foto a twitter",  // When you say "hide all",
								command: "PHOTOTW" // command "HIDEMODULES" will be executed
							},
							"APAGA": {
								pattern: "apágate",  // When you say "hide all",
								command: "APAGA" // command "HIDEMODULES" will be executed
							},
							"ENCIENDE": {
								pattern: "hola espejito",  // When you say "hide all",
								command: "ENCIENDE" // command "HIDEMODULES" will be executed
							},
							"SHOWMAPS": {
								pattern: "cómo voy a la universidad",  // When you say "hide all",
								command: "SHOWMAPS" // command "HIDEMODULES" will be executed
							},
							"HIDEMAPS": {
								pattern: "oculta el mapa",  // When you say "hide all",
								command: "HIDEMAPS" // command "HIDEMODULES" will be executed
							},
							SPOTIFY_PREVIOUS: {
								pattern: "canción anterior",
								command: "SPOTIFY_PREVIOUS"
							},
							SPOTIFY_PAUSE: {
								pattern : "para la música",
								command: "SPOTIFY_PAUSE"
							},
							SPOTIFY_PLAY: {
								pattern : "pon música",
								command: "SPOTIFY_PLAY"
							},
							SPOTIFY_NEXT: {
								pattern: "siguiente canción",
								command: "SPOTIFY_NEXT"
							},
							SPOTIFY_VOLUME: {
								pattern: "pon la música al volumen ([0-9]{1,2}[0]?|100)",
								command: "SPOTIFY_VOLUME"
							},
							SPOTIFY_SEARCH: {
								pattern: "pon (.*) en Spotify",
								command: "SPOTIFY_SEARCH"
							},
							SPOTIFY_SEARCH_PLAYLIST: {
								pattern: "playlist (.*) en Spotify",
								command: "SPOTIFY_SEARCH_PLAYLIST"
							},
							SPOTIFY_MA_PLAYLIST: {
								pattern: "(.*) mi playlist",   // (.*) eg: play my playlist / run my playlist etc... 
								command: "SPOTIFY_MA_PLAYLIST"
							},
							SPOTIFY_TRANSFER: {
								pattern: "pon la música en (.*)", // (.*)  is the name of your device
								command: "SPOTIFY_TRANSFER"
							},
							VOLUME_UP: {
								pattern: "sube el volumen",
								command: "CMD_VOLUME_UP"
							},
							VOLUME_DOWN: {
								pattern: "baja el volumen",
								command: "CMD_VOLUME_DOWN"
							},
							SET_VOLUME: {
								pattern: "pon el volumen general a ([0-9]{1,2}[0]?|100)",
								command: "CMD_VOLUME_SET"
							},
							
					}
			}
		},
		{
				module: "MMM-Hotword",
				config: {
						record: {
								recordProgram : "arecord",  
								device        : "plughw:1"
						},
						autostart:true,
						onDetected: {
								notification: (payload) => {
										return "ASSISTANT_ACTIVATE"
								},
								payload: (payload) => {
								return {
										profile: payload.hotword
								}
								}
						},
				},
		},
		{		module: "MMM-MotionDetector",
				config: {
						captureIntervalTime: 5000,
						scoreThreshold: 200,
						timeout: 300000
					}
		},
		{
            module: 'MMM-google-route',
            position: 'top_left',
            config: {
                key: ',
                directionsRequest:{
                    origin: ",
                    destination: "'
                }
            }
        },
        {
			module: "MMM-Spotify",
			position: "bottom_left",
			config: {

			}
		}
]
};

**Comment by Ejay-3D** [comment]
Can you try another module position? As well does the hook works? Can you
send some logs?

**Comment by F17MC** [comment]
Yes I tried other position, but is the same. 

How can I get the logs of the module?

EDIT:

with pm2 logs mm:

0|mm       |     at emitOne (events.js:116:13)
0|mm       |     at TLSSocket.emit (events.js:211:7)
0|mm       | TypeError: Cannot read property 'statusCode' of undefined
0|mm       |     at Request.request [as _callback] (/home/pi/MagicMirror/modules/MMM-Spotify/Spotify.js:189:23)
0|mm       |     at self.callback (/home/pi/MagicMirror/modules/node_modules/request/request.js:185:22)
0|mm       |     at emitOne (events.js:116:13)
0|mm       |     at Request.emit (events.js:211:7)
0|mm       |     at Request.onRequestError (/home/pi/MagicMirror/modules/node_modules/request/request.js:881:8)
0|mm       |     at emitOne (events.js:116:13)
0|mm       |     at ClientRequest.emit (events.js:211:7)
0|mm       |     at TLSSocket.socketErrorListener (_http_client.js:387:9)
0|mm       |     at emitOne (events.js:116:13)
0|mm       |     at TLSSocket.emit (events.js:211:7)

**Comment by F17MC** [comment]
I solve it. The problem was the connection with my Spotify account because I can't connect with VPN (I'm in other country now).

Sorry for the inconveniences.
