### ISSUE TITLE
Error in creating a Token 

### ISSUE THREAD

**Issue by ahward21** [skuethe/MMM-Spotify#163]
Hi, hope people are still active here,

I am setting up my first smart mirror, and I have followed all the steps so far. Copied in my Client id and Client secret. Added http://localhost:8888/callback to Redirect URLs in setting. 
When I run node first_auth.js  I get redirected to the web where I accept to MagicMirror changing my Spotify stuff then 
it redirects but never works.
https://prnt.sc/12kr2co

![Screenshot_2](https://user-images.githubusercontent.com/11218262/117299896-4cefec80-ae79-11eb-9408-6cccc45397a4.png)

Any idea's ? My client ID and secret were copied 1 for 1 , I've triple quadruple checked my 

Thanks for your time =)
Have a great day !

**Comment by ahward21** [comment]
edited code by accident when i was filling the client secret / id

**Comment by skuethe** [comment]
Great to hear that you where able to resolve it so quickly. Don't hesitate to come back if you have any other questions or problems.
