### ISSUE TITLE
How to hide module when not playing?

### ISSUE THREAD

**Issue by dmolony3** [skuethe/MMM-Spotify#165]
First of all this is a fantastic module. I have mine setup in the top bar and I was wondering how I can set it so that when the music is suspended the  module is hidden and when it is resumed/played it is visible. Would appreciate any tips!

**Comment by humbertovirtudes** [comment]
I remember this being the default behavior, but its also been a while since I looked at this code

**Comment by dmolony3** [comment]
Rereading my post I probably need to be more explicit. The controls and display are hidden but the space in the top bar is occupied still by the module. I was hoping to be able to set the height of the top bar to 0 while the music is suspended.

**Comment by skuethe** [comment]
Hey there @dmolony3,

if you are using `top_bar` as position, then you are using the "miniBar" style.
I currently don't have intentions to keep maintaining the `miniBar` design - see also the [release notes of v1.6.3](https://github.com/skuethe/MMM-Spotify/releases/tag/v1.6.3).

That being said, some input about your problem (without having more details):
- the top bar is controlled by `MM²`, so setting the height of that bar from within this module is out of the question - this could possibly break other modules
- as a workaround (without needing to modify this modules code), you could call `hide()` on it (a [build-in `MM²` function](https://docs.magicmirror.builders/development/core-module-file.html#this-hide-speed-callback-options)). This will suspend the module and hide it from your view. It should have the requested effect

This could be done with other modules (I am f.e. using `MMM-pages`, which does this in the background when switching pages).
It strongly depends how you interact with your MM² (touch / gestures / mobile remote / ...).

**Comment by dmolony3** [comment]
@skuethe Thanks for the detailed reply. That's a pity about dropping the miniBar but that's ok. I will probably switch to the default. I was trying to use hide() but I could not figure out where to place it. I tried placing it within the notificationReceived block in MMM-Spotify.js as below but it did not have the desired effect.

```
      case "SPOTIFY_PAUSE":
        this.sendSocketNotification("PAUSE")
        this.hide()
        break
```

**Comment by skuethe** [comment]
That is, because `notificationReceived` is primarily there for other modules to communicate with this module.
So if you would now send a `SPOTIFY_PAUSE` notification from **any** other module, this would be triggered. However, when you press "pause" this will not trigger this code.

What you could do (be aware, that automatic updates are not working any more when you modify code locally):

1. modify the `socketNotificationReceived` function in `MMM-Spotify.js` - specifically [lines 167 to 169](https://github.com/skuethe/MMM-Spotify/blob/c294785530c57a1a5ea803be6348499f35efb81e/MMM-Spotify.js#L167-L169)
2. change it from
    ```js
        if (noti.search("DONE_") > -1) {
          this.sendNotification(noti)
        }
    ```
    to something like
    ```js
        if (noti.search("DONE_") > -1) {
          this.sendNotification(noti)
          if (noti == "DONE_PAUSE") {
            this.hide()
          }
        }
    ```

Background: the `node_helper.js` file is sending this **socket**Notification when the pause button was pressed and the playback was successfully paused.

**Be aware that this will hide this module until you "unhide" it**. So you need to call `show()` on it if you want to "get it back". This, again, depends how you start playing songs in your setup.
Maybe extending the code above to something like:

```js
    if (noti.search("DONE_") > -1) {
      this.sendNotification(noti)
      if (noti == "DONE_PAUSE") {
        this.hide()
      }
      if (noti == "DONE_PLAY") {
        this.show()
      }
    }
```
could already do the trick. But you would need to evaluate that.

**Comment by dmolony3** [comment]
Thank you so much for all this detail. I had been wondering how the notifications worked and now I get it. I tried changing as to your suggestion but it did not work. On printing *noti* to the console from what I can tell "DONE_PAUSE" or "DONE_PLAY" are never sent. I do see "CURRENT_PLAYBACK" and "CURRENT_NOPLAYBACK" coming from the *updatePulse* async function. I then added hide() when "CURRENT_NOPLAYBACK" is triggered and show() when  "CURRENT_PLAYBACK" is triggered. 

```
      case "CURRENT_PLAYBACK":
        if (this.hidden) {
            this.show()
        }
        if ((this.config.allowDevices.length === 0) || (this.config.allowDevices.length >= 1 && this.config.allowDevice$          this.volume = payload.device.volume_percent
          this.sendSocketNotification("UNALLOWED_DEVICE", false)
          this.updateCurrentPlayback(payload)
        } else {
          this.sendSocketNotification("UNALLOWED_DEVICE", true)
          this.updatePlayback(false)
        }
        break
      case "CURRENT_NOPLAYBACK":
        this.updatePlayback(false)
        this.hide()
        break
```

I also disabled the "SUSPENDING" sendsocketNotification in MMM-spotify.js. 
```
  suspend: function() {
    console.log(this.name + " is suspended.")
    //this.sendSocketNotification("SUSPENDING")
```
This appears to work though I have not extensively evaluated it.

**Comment by skuethe** [comment]
Any reason why you disabled sending the `SUSPENDING` socketNotification?
This stops periodic API communication with Spotify in the background when not using this module.


> On printing noti to the console from what I can tell "DONE_PAUSE" or "DONE_PLAY" are never sent.

Interesting. I will take a look at that.

So is the behaviour of the "hidden" app what you expected when opening this PR?

**Comment by dmolony3** [comment]
> Any reason why you disabled sending the `SUSPENDING` socketNotification?
> This stops periodic API communication with Spotify in the background when not using this module.

It did not seem to start backup/unhide again if paused for a longish period of time. 


> So is the behaviour of the "hidden" app what you expected when opening this PR?

Yes, I think this effect is what I am looking for. I will close the issue and thanks for your help!
