### ISSUE TITLE
How to use notification control music?

### ISSUE THREAD

**Issue by Luckychuan** [skuethe/MMM-Spotify#19]
I don't know how to edit the notification code. such as:   this.sendNotification("SPOTIFY_PAUSE")  whick file should I add these code?

**Comment by eouia** [comment]
well, those notifications are prepared for module developer. are you developing your module? or via which module do you want to control?

**Comment by Luckychuan** [comment]
@eouia  
Thanks for helping me. I use this module [MMM-GoogleAssistant](https://github.com/gauravsacc/MMM-GoogleAssistant).

I want to test:  when ON_RECOGNIZING_SPEECH_FINISHED,it send a notification to pause music.I add  this.sendNotification("SPOTIFY_PAUSE")   to [MMM-GoogleAssistant.js](https://github.com/gauravsacc/MMM-GoogleAssistant/blob/master/MMM-GoogleAssistant.js) line:55.but when speech finished , it dosen't pause music.
  
```
else if (notification == 'ON_RECOGNIZING_SPEECH_FINISHED') {  
       this.sendNotification("SPOTIFY_PAUSE"); 
       this.userQuery = payload;   
      this.processing = true;   
      delay = 0;   
    }
```

And I see your code  `case "SPOTIFY_PAUSE"`  and `this.sendSocketNotification("PAUSE");` in  notificationReceived function is called,but music in chrome spotify doesn't pause .

**Comment by eouia** [comment]
It seems you have a skill of dev. So, you can inspect `Spotify.js` whether the API is called exactly. `.pause()` and `.doRequest()` would be checkpoints.

**Comment by Luckychuan** [comment]
I add two alert in notification recevied function
```
   case "SPOTIFY_PAUSE":
        alert("notification receive");
        this.sendSocketNotification("PAUSE");
        alert("after sendSocketNoti");
        break
```
I see two alerts show in my screen,so I guess(I have no experience in JavaScript) this code `this.sendSocketNotification("PAUSE");` is called.

And I add alert to pause function in Spotify.js, the alert doesn't show.
```
pause(cb) {
    alert("spotify.js");	
    this.doRequest("/v1/me/player/pause", "PUT", null, null, cb)
}
```

**Comment by eouia** [comment]
<img width="1073" alt="spo" src="https://user-images.githubusercontent.com/1720610/58270782-7eea1000-7d82-11e9-87b2-9db52498991d.png">
Well, My test dummy module can emit SPOTIFY_PAUSE successfully. Without no problem.

and as you see, Spotify be paused, and return DONE_PAUSE message. Hmmm.

**Comment by Luckychuan** [comment]
<img width="988" alt="捕获" src="https://user-images.githubusercontent.com/23069232/58332683-54758100-7e6e-11e9-92b5-ca0d55ea146b.PNG">
I see this in terminal.Is there any error?

**Comment by eouia** [comment]
@Luckychuan If you have `connection hang up` problem, set `updateInterval` to 2000 or 3000. Too many connection could make  connectivity issue with Spotify server.

**Comment by Luckychuan** [comment]
I guess  socketNotificationReceived in node_helper.js  cannot work

```
onStart: function() {
    if (!this.config.onStart)	return 
	console.log("onstart function");
	this.sendSocketNotification("ONSTART", this.config.onStart)
  },
```
```
socketNotificationReceived: function(noti, payload) {
    if (noti == "INIT") {
      this.initAfterLoading(payload)
      this.sendSocketNotification("INITIALIZED")
    }

    if (noti == "ONSTART") {
      console.log("onstart socketNotificationReceived");
      payload.position_ms = 0
      if (payload.search) {
        var param = {
          q: payload.search.keyword,
          type: payload.search.type,
        }
        var condition = {
          random: payload.search.random,
          autoplay: true,
        }
        this.searchAndPlay(param, condition)
```
“ onstart function” shows but "onstart socketNotificationReceived" doesn't
<img width="270" alt="捕获" src="https://user-images.githubusercontent.com/23069232/58532672-db34b000-8218-11e9-9fe1-b162cdc475a3.PNG">

**Comment by eouia** [comment]
log of `node_helper.js` is not shown on front-end dev console. it will be logged on backend-log. see your pm2 log or get it by `npm start dev` and see the terminal.

**Comment by Luckychuan** [comment]
```
  pause(cb) {
	 console.log("puase spotify.js");
    this.doRequest("/v1/me/player/pause", "PUT", null, null, cb)
  }
```

```
 doRequest(api, type, qsParam, bodyParam, cb) {
	 console.log("do request");
    var authOptions = {
      url: "https://api.spotify.com" + api,
      method: type,
```
<img width="250" alt="捕获" src="https://user-images.githubusercontent.com/23069232/58536442-25bb2a00-8223-11e9-94cb-3906c2e72cad.PNG">
I see the log.but music in my Android phone cannot pause.

**Comment by eouia** [comment]
Hmmm. weird.
1) Your account is premium?
2) Both accounts (this module and your android phone) are the same?

**Comment by Luckychuan** [comment]
1. not premium
2.the same 
<img width="229" alt="捕获" src="https://user-images.githubusercontent.com/23069232/58536762-0bce1700-8224-11e9-8a58-24da0015e368.PNG">
<img width="241" alt="捕获" src="https://user-images.githubusercontent.com/23069232/58536999-826b1480-8224-11e9-9245-fb94091b5a3f.PNG">


Could you tell me the url of pause music ,I try url in my bowser to see whether it can pause music.

**Comment by eouia** [comment]
Only premium user can control devices with API.

**Comment by Luckychuan** [comment]
yeah， now I can control music.Thanks your help.close it.
And you should note that " premium only" in README

**Comment by eouia** [comment]
<img width="514" alt="sp" src="https://user-images.githubusercontent.com/1720610/58554212-b0495c80-8216-11e9-834d-de31c2245e4e.png">
:)
