### ISSUE TITLE
Need to add progress Bar 

### ISSUE THREAD

**Issue by Ejay-3D** [skuethe/MMM-Spotify#2]
css and main js/ enhancement needed.

**Comment by eouia** [comment]
This is just working demo to show how to ise Spotify.js :)


I think its possible with current playBack. The only concern is too many api polling. Anyway already playBack is calling per 1,2 secs.

**Comment by Ejay-3D** [comment]
I'm raising those issues as todo list ;)

**Comment by ejay-ibm** [comment]
added for now with all reference to make it work and display correctly.  
progress.innerHTML  = `<i class="fas fa-clock"></i>` + " " +  Math.floor(this.currentPlayback.progress_ms / 60000) + ":" + ((this.currentPlayback.progress_ms % 60000)$

Progress bar is a nice looking feature But for now to avoid calling api to refresh actual current song position time. 

I'm thinking of getting the value on status update as it is now, and start a 'timer' that will add its value to the initial value. by incrementing the seconds. 

Need to search how to do that.

**Comment by Ejay-3D** [comment]
Added Current track time for now . 
Will check how to implement a progress bar .  ( Low priority )
