### ISSUE TITLE
Unable to generate tokens with firstrun on docker

### ISSUE THREAD

**Issue by j33p4meplz** [skuethe/MMM-Spotify#20]
i've got MM hosted in a container on the network and my mirror just kiosks a webpage from it, i'm having some trouble generating the token with this. I've got a feeling its returned in the URL that wont open, but i've got no reference for what it should look like to manually create the file.

**Comment by eouia** [comment]
Sorry, I've not tested on Docker environment. If you have a trouble to allow permission after login (Usually page would not be changed after login), Clear cache of brwoser or use another browser.

**Comment by j33p4meplz** [comment]
I'm not running it locally, so it spits out a link for me to go to. I can grant it permission, but its not able to access the /callback url, even with using the host IP and port. I have a feeling the token is actually in the URL itself though. Do you have a sample of the auth file you could put up? That may let me create it and solve the issue.

**Comment by eouia** [comment]
Different with usual oAuth process, Spotify Authentification needs POST method to get token. So, it is not simply done by using URL on the browser manually.
See this section and try to implement by yourself, if could. https://developer.spotify.com/documentation/general/guides/authorization-guide/#authorization-code-flow
