### ISSUE TITLE
Module only shows Spotify logo, no errors

### ISSUE THREAD

**Issue by s1h4d0w** [skuethe/MMM-Spotify#21]
So I just set up Magic Mirror on a fresh RPi, installed a module for a todo list and then installed this module. I created an app on developer.spotify.com, got the two keys, ran the script to configure the module, put it in the config, but when I load Magic Mirror it only shows the Spotify logo.

I checked the logs and the developer console but I can't find any errors. I double checked my keys and the setup of my app on the developer site, but I can't find any issue.

Any help on getting this to run and where to look for issues would be greatly appreciated.

**Comment by eouia** [comment]
This module is showing current playback. It means, unless you play Spotify on your device - even including Raspotify on your device - nothing will be shown.
If you have installed Raspotify on your RPI and/or at least set `onStart` to play something on your existing device, the playback would be started. 
Or you can activate the module by playing Spotify on your device - e.g: your Spotify app on your smartphone.

**Comment by s1h4d0w** [comment]
Ah, that explains it, thank you!
