### ISSUE TITLE
ocan not generate token, cannot find module "opn" error

### ISSUE THREAD

**Issue by zallard** [skuethe/MMM-Spotify#22]

**Comment by zallard** [comment]
Hi all.
After installing the module, I couldn't generate the token with node_auth.js
It was giving me can not find module "opn" error.
After digging the net a bit, it appears that the package has been deprecated.
Now it's named "open"
to fix the issue, edit Spotify.js
and replace at line 11
const opn = require("opn")    by
const opn = require("open")

then install open package.
type :
npm install open

hope it helps, and please update the code.

**Comment by eouia** [comment]
You are right. `opn` seems deprecated. Thanks for report.
