### ISSUE TITLE
Module not showing up

### ISSUE THREAD

**Issue by ivanovd** [skuethe/MMM-Spotify#23]
I installed the module with no errors. I have the following config:

```
{
  module: "MMM-Spotify",
  position: "bottom_left",
  config: {
    style: "default", // "default" or "mini" available
    control: "hidden", //"default", "hidden" available
    updateInterval: 1000,
    onStart: null, // disable onStart feature with `null`
    //allowDevices: [], //If you want to limit devices to display info, use this.
    // allowDevices: ["RASPOTIFY", "My iPhoneX", "My Home speaker"],
  }
},
```

I have added the my client ID and secret to spotify.config.json and generated the token.json file

However when I start MM I don't get anything in that position (I tried different positions), not even a logo and the music is playing on my Spotify account.

In the pm2 logs I have the following:
```
Module helper loaded: MMM-Spotify
Initializing new module helper ...

Connecting socket for: MMM-Spotify
[SPOTIFY_AUTH] Token is fresh.
```

I have no errors in /home/pi/.pm2/logs/mm-error.log

**Comment by ivanovd** [comment]
Disregard ... I realised that the default config doesnt have classes and I am using facil recognition module which makes that mandatory.

**Comment by eouia** [comment]
Sorry I'm on vacation so couldn't have answered. If you have any issue, feel free to leave.
