### ISSUE TITLE
Error with last update changing opn to open

### ISSUE THREAD

**Issue by jcmarinn** [skuethe/MMM-Spotify#25]
I pulled the last updated where you change "opn" to "open" but npm on my machine was not updated and could not find module open

App threw an error during load
Error: Cannot find module 'open'

I have installed open "npm install open" and now it's working but you may wish to warn users

**Comment by eouia** [comment]
Thanks for your kind report. Usually, it should be installed by `npm install` after `git pull` but sometimes it could not be installed properly. I don't know why, but I'll add this into `README.md`
