### ISSUE TITLE
Paus & Play button is in wrong order.

### ISSUE THREAD

**Issue by maxim0x2929** [skuethe/MMM-Spotify#26]
When the music is playing it is suppose to display the paus sign
When the music is paused it is suppose to display the play sign

Right now its the other way around 

Just a minor thing that bugs me :)

**Comment by eouia** [comment]
Well, I think it is not bug, just different culture as it were. (I believe. :D)
Anyway, you can change the icons.
https://github.com/eouia/MMM-Spotify/blob/ccc67e0396e0f29992023f6f405e129c57b4b9d4/MMM-Spotify.js#L239-L250
modify "dataset.icon" to whatever you wish. (for the icon, See the iconify: https://iconify.design/icon-sets/

**Comment by maxim0x2929** [comment]
Okey haha :)
Thank you for pointing me to where i can edit!

Thank you also for this module for the mm. It was verry simple to configure and works super good on the pi touch screen :)
