### ISSUE TITLE
Module Doesn't Reload After Restarting Spotify

### ISSUE THREAD

**Issue by georgeglessner** [skuethe/MMM-Spotify#28]
When I quit Spotify, the module disappears as expected. But when I start Spotify back up the module doesn't re-appear. Any suggestions? I have tried adding updateInterval to no avail.

**Comment by eouia** [comment]
Where is your spotify playback(player) working? and share with me your config.

**Comment by georgeglessner** [comment]
Plays from iPhone or EchoDot. Config is as follows:

```

module: "MMM-Spotify",                                                                         
position: "upper_third",                                                                        
config: {
     updateInterval: 1000,
}

```

**Comment by eouia** [comment]
Hmmm.. very weird. In my test, there seems nothing wrong. I'll inspect more.

**Comment by georgeglessner** [comment]
So just did more testing. It works perfect from web player and echo dot. Just not iPhone which is no big deal. You can close this issue out if you would like.
