### ISSUE TITLE
Position overlay top module

### ISSUE THREAD

**Issue by Ejay-3D** [skuethe/MMM-Spotify#3]
![Capture d’écran 2019-03-16 à 08 48 44](https://user-images.githubusercontent.com/38557267/54472407-5a911680-47c8-11e9-9c35-2f30731dde1d.png)

**Comment by eouia** [comment]
This is working demo. :) you can make better

**Comment by Ejay-3D** [comment]
Yeah ! By the way I love the style you gave with the blurry cover in background

**Comment by ejay-ibm** [comment]
Fixed, made change in css will commit change. and put ref here before closure

**Comment by Ejay-3D** [comment]
Fixed

**Comment by eouia** [comment]
I saw your fixation. nice try. but...
It will be problem on `bottom_left` also.
The issue could be fixed by assign `position:relative` to `#SPOTIFY`
