### ISSUE TITLE
i only can see the spotify logo when i start playing

### ISSUE THREAD

**Issue by lentechforu** [skuethe/MMM-Spotify#31]
I have the issue that if  i start to play a song on my phone , i only can see the spotify logo on the magic mirror screen. Can somebody help me?
Thx!

**Comment by eouia** [comment]
Are you using Spotify premium account?

**Comment by lentechforu** [comment]
Yes I do.

**Comment by eouia** [comment]
After MM is executed, the spotify logo is showing, Play any song on your iphone app (Same account with your module), At that time, what log says? (You can check it with `pm2 show log` or instead `pm2`, use `npm start dev`)

**Comment by lentechforu** [comment]
**pi@SmartMirror:~** $ pm2 show log
[PM2][WARN] logs doesn't exist
**pi@SmartMirror:~** $ npm start dev show log
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
npm ERR! path /home/pi/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-12-27T08_44_08_404Z-debug.log

**Comment by lentechforu** [comment]
This is what i get. I'm just a beginner, so thank you for helping me.

**Comment by eouia** [comment]
Sorry for late answer. I was hospitalized.
`npm start dev` should be executed in your MagicMirror directory.
and should stop `pm2` before.

**Comment by sankalp1857** [comment]
Please go ahead and try switching your internet as well. In my case , the speed was slow and when I switched the network, it worked fine.

**Comment by EscoR85** [comment]
I have the same problem  I tried a couple of times and then gave up.
The next morning the autostart brings the MM back and everything works again - maybe it was a spotify problem or a restart was  necessary...

Thanks for the nice app
