### ISSUE TITLE
keep display always active

### ISSUE THREAD

**Issue by DrPootarski** [skuethe/MMM-Spotify#34]
Is there a way to keep the display active? i.e. just keeping the last song you played as a reference

**Comment by bugsounet** [comment]
Hi,
I think by editing MMM-Spotify.css
Comment this part : 
```
/*
#SPOTIFY.inactive {
  display:none;
}
*/
```
Module is always displayed (not tested)

**Comment by DrPootarski** [comment]
I tried that it ends up just showing the spotify logo

**Comment by eouia** [comment]
@DrPootarski 
While your Spotify-device(e.g: Sonos Smart speaker, Your iPhonne...) is active, the last song information will remain. But if no active Spotify-device is not on at the moment of this module be running, Spotify doesn't know what is last played. Sorry, it doesn't work like your wish.
