### ISSUE TITLE
1.2 Multi-account error

### ISSUE THREAD

**Issue by jcmarinn** [skuethe/MMM-Spotify#36]
Hi

I just updated to latest branch (1.2) but it giving me an error that I think it's related to the array where you read the config.

It gives a node error like `this.spotifyConfigurations.forEach is not a function`

This also happens with the firs.auth.json script

I went back to the previous build and everything is working again

Is there anything that needs to be changed or updated on the config file for the new build to work?

**Comment by VaticanGM** [comment]
I came here to post the same issue as @jcmarinn. I wasn't sure if was related to the OS upgrade I did prior to updating to the latest branch.
