### ISSUE TITLE
voice command "start spotify" doesnt work, while playing everything works fine tho

### ISSUE THREAD

**Issue by markusloe123** [skuethe/MMM-Spotify#38]
like the title is already telling everything lol
is this a general problem or did i do something wrong?

Thanks in advance for your help guys!

**Comment by bugsounet** [comment]
hi,
You can add prepared [Spotify recipe](https://github.com/eouia/MMM-AssistantMk2/blob/master/recipes/with-MMM-Spotify.js) for advance vocal function

read [there](https://github.com/eouia/MMM-AssistantMk2/wiki/Prepared-recipes#with-mmm-spotifyjs) for more information
