### ISSUE TITLE
SPOTIFY_PLAY Notification

### ISSUE THREAD

**Issue by victor-paumier** [skuethe/MMM-Spotify#41]
Hi, 
First thanks for this repository, it is AWESOME!

I am having a problem using the SPOTIFY_PLAY Notification.
Regarding [the documentation](https://developer.spotify.com/documentation/web-api/reference/player/start-a-users-playback/), the problem seems to be the endpoint parameters.
To fix it, `spotify:track:3ENXjRhFPkH8YSH3qBXTfQ` must be replace by `{"context_uri": "spotify:track:3ENXjRhFPkH8YSH3qBXTfQ"}`

Cheers

**Comment by eouia** [comment]
You are right. I'll fix it.
Anyway, `context_uri` doesn't allow `track`. So If you need tracks, use `uris: []` instead.
