### ISSUE TITLE
Control of different devices .....

### ISSUE THREAD

**Issue by jamesvcc** [skuethe/MMM-Spotify#43]
Hi, I have this up and running and its great.  However, I can use this module fine to control Spotify connect on most of the devices I have - except Sonos speakers.

If I choose a Sonos speaker as an output (Spotify Connect) device then the module will no longer start/stop/skip/reverse etc... through the playlist.  If I then choose a different type of output device then control comes back again.

Seems to be that it does not like controlling Connect devices that are Sonos.  Any ideas?

Also, a question - how can I use the module to change the volume of the output device.  I cannot easily code stuff so any explanation need to be simple for me.

Thanks.

**Comment by eouia** [comment]
Hmmm. 
No idea abou it. Devices list is derived from Spotify Server, So, Server wouldn't send the device info, it cannot be controlled, and nothing to do by this module.

For the second question, Which method are you considering to control the volume? H/W Button? touchscreen? anyway, it can controllable through ` this.sendNotification("SPOTIFY_VOLUME", 50)`. So if some module can emit custom notification, it could be done.
