### ISSUE TITLE
volume up/down

### ISSUE THREAD

**Issue by Kraftprotzi** [skuethe/MMM-Spotify#44]
hey,
first of all great work. Everythink works great.
Just a question:
Is there a variable with the current volume information of the external speaker device (0-100)? I want to add the recipte "Volume-up" and "Volume-down".
Thanks for you help and for this great MM-module anyway.

**Comment by eouia** [comment]
The only problem is getting current volume is not so easy. In that APIs there is no API for current volume. By getting device list, there be volume info but that information is used on startup, So if volume would be changed in external device, the current volume value will not be tracked. Sorry.

Use MMM-Volume instead.
