### ISSUE TITLE
Handling of multiple accounts does not work

### ISSUE THREAD

**Issue by djdocta** [skuethe/MMM-Spotify#45]
Hi,
I've installed the latest version of MMM-Spotify and tried to make the new feature of handling multiple accounts work but the feature is not working. 

Behaviour : 
If I put several accounts in my spotify.config.json file, the application will not work (with none of the accounts). 
If I put one of the accounts (separatly - one at a time), they will work without any issue. 

Question : 
Is this the normal behaviour ? What should I do to make them work together ? 
When they do work, if both account play music at the same time, info from what account would be shown at the screen  ? 

My config fie : 

[
  {
      "USERNAME": "RASPED",
      "CLIENT_ID" : "MY_ID",
      "CLIENT_SECRET" : "MY_SECRET",
      "AUTH_DOMAIN" : "http://localhost",
      "AUTH_PATH" : "/callback",
      "AUTH_PORT" : "8888",
      "SCOPE" : "user-read-private app-remote-control playlist-read-private streaming user-read-playback-state user-modify-playback-state",
      "TOKEN" : "./rasped_token.json"
  },
  
  {
      "USERNAME": "RASPI",
      "CLIENT_ID" : "MY_ID2",
      "CLIENT_SECRET" : "MY_SECRET2",
      "AUTH_DOMAIN" : "http://localhost",
      "AUTH_PATH" : "/callback",
      "AUTH_PORT" : "8888",
      "SCOPE" : "user-read-private app-remote-control playlist-read-private streaming user-read-playback-state user-modify-playback-state",
      "TOKEN" : "./raspi_token.json"
  }
]

**Comment by eouia** [comment]
What log says?

**Comment by djdocta** [comment]
Havnt check...What should I type in order to enable logs ?

**Comment by eouia** [comment]
The easiest way to check backendlog on realtime, 
- To make things simple, remove all other modules except MMM-Spotify (and related modules, if exist)
- If you are using `pm2` to manage execution of MM, stop it first.
- Go to MagicMirror directory and execute `npm start dev`. It will show the backend log on your terminal shell.

**Comment by djdocta** [comment]
Eouia,
thanks for the support but case can be closed. 
I did a retest this morning and the multiple account was working fine. 
Can you please share a last point : I did run of the MM with "npm start dev" but how can I activate something like a "debug mode" where I can see exactly what steps are done ? 
For ex. : "I say something to the mirror": 
 -> sentence "blblabla" is catched by the mirror from module MMM-ThisIsTheModule
 -> MMM-ThisIsTheModule calls MMM-ThisisThemoduleCalled with arguments "youShouldDoThis"
 -> MMM-ThisisThemoduleCalled executed the actions "ThisIsTheAction" ?

To be short I want to follow what is done in order to see why sometimes some actions are catched or not between Hotword-Mk2-Spotify. 

Thanks for the great work.

**Comment by eouia** [comment]
Another issue?

Anyway, you probably are trying to use Hotword, AMK2 and Spotify. 
There be many issues on combination of modules.
You should check these first;
- Where the issue lays on? modules' working or interaction between specific modules?
=>
  - Check each module independently. Whether being loaded and started any suspicious log message on backend log and frontend log.
  - Check the interactions. Usually it is done by notification between modules. `clock` module is tricky useful for that purpose, because she spits out all notifications her received on frontend log.

To trace/debug code, Hmmmm.. for the developer, modifying source to spit out some log on suspicious point or to set stoppoint and tracing  is not difficult. But not for the developer... I can't say anything.

**Comment by djdocta** [comment]
The thing is that ... 
When I send notifications to MMM-Spotify, must of them work excpt the ones where arguments are past.
Ex. : pattern : " ( .* ) on spotify" or "spotify volume ( .* ) " 
The sentences are catched correctly but MMM-Spotify is not doing any action. 
I have the feeling that the argument (.*) is not translated/received correctly, thats why I wanted to know if there was a way to "see" what exactly is send out and done via debugging or something.

**Comment by bugsounet** [comment]
sorry for the very last response.
I will see as soon as possible

**Comment by bugsounet** [comment]
i try with lastest version of `MMM-Spotify` (v1.3.2) volume support with an premium account and it works
i just says with original Spotify recipe: `jarvis ... Spotify volume **value**`
**value** is a number between 0 - 100

**Comment by djdocta** [comment]
@bugsounet 
This can be closed.
It was a manual error.
