### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by magicmirror2020** [skuethe/MMM-Spotify#47]
Any suggestions with these JSON errors on step 4 of the install. No allowance dialog popup opens.

<img width="327" alt="1" src="https://user-images.githubusercontent.com/56414705/79930501-a88a3c00-8416-11ea-901e-dfeec9c1b1d7.png">
<img width="335" alt="2" src="https://user-images.githubusercontent.com/56414705/79930503-a88a3c00-8416-11ea-86ac-99210d2e440b.png">

**Comment by magicmirror2020** [comment]
It was just a syntax error in my spotify.config.json, I got the spotify popup

**Comment by eouia** [comment]
Nice to hear that.
