### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by p10dulkar** [skuethe/MMM-Spotify#49]
**This is not an issue** 
just a **noob** query

I just want to know how do notifications work  for magic mirror or every module
do I have to type them in the config file or every module's js file 
or do I type them through keyboard just like we do chat 
or through telegram 
I really searched everywhere IMO but I don't know why I am not finding a solution to it 
but as u have built so many awesome modules and even reply to every one of my queries till now hence asking u 

how to send this, type, show, send, work, where to put  these notifications 
Example : this.sendNotification("SPOTIFY_SEARCH", {type:"artist,playlist", query:"michael+jackson", random:false})

**Comment by eouia** [comment]
What user-input method your mirror has? (keyboard? button? mic?)
Or what real use-case or scenario are you considering?

**Comment by p10dulkar** [comment]
I have a wireless usb remote connected ic also connected for Google assistant but mostly I use control it SSH

**Comment by eouia** [comment]
You mean, you want to control MM through SSH terminal (in other computer) on real usage?

In that case, I think `CURL` would be the most common way to send your intention. (Or you could make some script about it)
Some modules - like MMM-NotificationTrigger ..  - Could accept HTTP POST/GET request. MMM-NotificationTrigger can translate that request to notification of MM.

But I still feel some weirdness about controlling MM with SSH. Never imagined. :D

MMM-TelegramBot can also emit custom notification with `/notification` command. Or you can make your own commands for convenient usage.

**Comment by p10dulkar** [comment]
Okay okay 
Now just tell me how to send this  below notification through telegram bot or keyboard 

this.sendNotification("SPOTIFY_SEARCH", {type:"artist,playlist", query:"michael+jackson", random:false})

**Comment by eouia** [comment]
If you are using MMM-TelegramBot, 
```
/notification SPOTIFY_SEARCH {type:"artist,playlist", query:"michael+jackson", random:false}

```
Will work.
But If I were you, I'll make a custom command for that purpose. Anyway above is somewhat long to type for me. :P

**Comment by p10dulkar** [comment]
the above command gives an error that notification payload is not proper 
Even tried ur default example of nofication command on ur telegram bot page still same error 


I'll sure be making custom commands for evry notification 

And one more thing should I create a new thred for this below issue in ur mmm-assistantmk2 
 when I install Google assistantmk2 
I am not able to install Alexa it gives an error that device resource is busy or not responding 
Do I have to attach one more mic for Alexa or is there any way to work both of them at the same time individually just by saying the hotword

**Comment by eouia** [comment]
What kind of error? More details are needed.

**Comment by p10dulkar** [comment]
/notification SPOTIFY_SEARCH

{type:"artist, playlist", query:"michael+jackson", random:false})

**Notification payload is not proper.**

{type:"artist, playlist", query:"michael-jackson", random:false})

10:24 PM

/notification SHOW_ALERT {"title":"test",

"timer":1000))notification SHOW_ALERT {"title":"test", "timer":1000}) 

**Notification payload is not proper.**

{"title":"test",

"timer":1000})

10:25 PM

**Comment by eouia** [comment]
{type:"artist, playlist", query:"michael+jackson", random:false}**`)`** <--- the last brace ")"

**Comment by p10dulkar** [comment]
I feel too dumb now :p 
Thank you so much for ur patience problem is solved now
