### ISSUE TITLE
Pause break progress bar status 

### ISSUE THREAD

**Issue by Ejay-3D** [skuethe/MMM-Spotify#5]
progress bar is 'null' on start an pause. 
Progress bar should not be shown when nothing is loaded

**Comment by eouia** [comment]
I think it could be just style matter. I don’t care whether bar is displayed or not (or showing last position or not) when not being used.
However, you can fix it(showing last position by setting this.currentPlayback with current gotten) or hide it(by style.display:none when paused)

**Comment by eouia** [comment]
fixed:
- empty progress bar will not be displayed on nothing to play
- on Pausing, last progress bar will be remain.
