### ISSUE TITLE
Error in authenication flow!

### ISSUE THREAD

**Issue by cain0z** [skuethe/MMM-Spotify#82]
Hi,
i am getting an error when trying to authenticate multiple accounts
doesn't change depending on the order I attempt.

I can do one or the other, but neither together.

**Comment by SuperfrogMe** [comment]
I have exactly the same issue.
Works perfectly for the first account, but have an "Error in authentication flow!" for the second.

**Comment by guisimo** [comment]
i have the same issue but in my first login

**Comment by guisimo** [comment]
It says INVALID_CLIENT: Invalid redirect URI

**Comment by bugsounet** [comment]
retry with lasted version

Please Read the `ReadMe` file for installing correctly

**Comment by SuperfrogMe** [comment]
> retry with lasted version
> 
> Please Read the `ReadMe` file for installing correctly

Hi bugsounet.
Thanks again for your work !

Again, in my case, I have an "Error in authentication" for the second account.
No matter which one is the first or second account. Both accounts work alone.

Is there a file or logs I can send you to help ?

**Comment by SuperfrogMe** [comment]
I still have the same message in console for the 2nd account, and can't use the module for our 2 accounts =/

After a moment, the browser return "ERR_EMPTY_RESPONSE".

**Comment by bugsounet** [comment]
updated to v1.5.0. Read new readme
