### ISSUE TITLE
Can you config to hide spotify logo?

### ISSUE THREAD

**Issue by ezar** [skuethe/MMM-Spotify#85]
Can you config to hide spotify logo?

<img width="436" alt="Screenshot 2020-05-23 at 08 56 21 1" src="https://user-images.githubusercontent.com/42736/82724044-713bd300-9cd3-11ea-96ae-fe1a5811a3e9.png">

Regards,

**Comment by bugsounet** [comment]
Spotify logo hide automaticaly, if your configuration have no error.

Check your spotify.config.json and token if exist

**Comment by ezar** [comment]
It's all ok.
Can I delete token.json?

**Comment by bugsounet** [comment]
nop token.json is needed

**Comment by ezar** [comment]
I delete token and reconfigure all. Works now!
