### ISSUE TITLE
Recongnition of multiple Spotify Account

### ISSUE THREAD

**Issue by Badabing77** [skuethe/MMM-Spotify#87]
Hi there

I have Setup all succesfully. But after I have started the MM, the Spotify Module only shows the 2nd Spotify Account. Any suggestions what might be the problem? Thanks!

Badabing77

**Comment by bugsounet** [comment]
by default:
MMM-Spotify load the account defined by default in your config.js:
```
accountDefault: 0, // default account number, attention : 0 is the first account
```

If you wan to change account you have to use another module to send a notification to MMM-Spotify 

to change to wanted account
```
SPOTIFY_ACCOUNT: change account. payload is the USERNAME defined in your account in spotify.config.json file
this.sendNotification("SPOTIFY_ACCOUNT", "premium")
payload could be the number of the account. attention: for first account, number is 0

this.sendNotification("SPOTIFY_ACCOUNT", 0)
```
