### ISSUE TITLE
Play a specific playlist from GA

### ISSUE THREAD

**Issue by JoshuaEPSamuel** [skuethe/MMM-Spotify#94]
I believe the easiest way to play a specific Spotify playlist from Google Assistant is via notifications?

If so can anyone help clarify the whole notification system? The generic MM site doesn't explain how to implement from what I can see...

This is what I've done so far, so that the voice command 'play clarity' will play the playlist:
**MMM-GoogleAssistant/Recipes/with-MMM-Spotify.js'**
`var recipe = {
  transcriptionHooks: {
...
   },
    "PLAY_SPOTIFY" : {
      pattern: "play clarity",
      command: "PLAY_SPOTIFY"
    },
  },
  commands: {
...
"PLAY_SPOTIFY": {
      notificationExec: {
        notification: "SPOTIFY_PLAY"
      },
      soundExec: {
        chime: "open"
      }
    },`

**MMM-Spotify/node_helper.js**
`module.exports = NodeHelper.create({
...
searchAndPlay: function (param, condition) {
...
    }
    this.sendNotification("SPOTIFY_PLAY", {"context_uri": "spotify:album:1Je1IMUlBXcx1Fz0WE7oPT"})
    }
    this.spotify.search(param, (code, error, result) => {
...`

**Comment by bugsounet** [comment]
Hi,
I use native response of google for playing album,playlist or single music.
I use no recipes actually, maybe just for using transfert, account or volume
I only use [MMM-Assistant2Display](https://github.com/bugsounet/MMM-Assistant2Display) with spotify support

**Comment by JoshuaEPSamuel** [comment]
> Hi,
> I use native response of google for playing album,playlist or single music.
> I use no recipes actually, maybe just for using transfert, account or volume
> I only use [MMM-Assistant2Display](https://github.com/bugsounet/MMM-Assistant2Display) with spotify support

Native response of google for playing music (album/playlist/song) plays it on YouTube for me. What I'm trying to do is play it through Spotify via send notifications, as far as I'm aware this is possible however I don't know how to implement send/receive notifications as it has been removed on the MM website

**Comment by bugsounet** [comment]
> this.sendNotification("SPOTIFY_PLAY", {"context_uri": "spotify:album:1Je1IMUlBXcx1Fz0WE7oPT"})

you can't sendNotification inside a node_helper file

> notificationExec: {
        notification: "SPOTIFY_PLAY"
      },

you don't send the payload only a notification with SPOTIFY_PLAY and an NULL or undefned payload
maybe with in addition of notification
`payload: {"context_uri": "spotify:album:1Je1IMUlBXcx1Fz0WE7oPT"}`
(not tested)
