### ISSUE TITLE
MMM-Spotify module not launching

### ISSUE THREAD

**Issue by ngdemigod** [skuethe/MMM-Spotify#96]
All of a sudden the module stopped launching when I start magic mirror. I have no idea why

**Comment by bugsounet** [comment]
I have an issue with token refresh.
maybe it's that.
I'm trying to fix it actually and i'm testing it

**Comment by ngdemigod** [comment]
Great, let me know what to do to fix it after your done testing

**Comment by ngdemigod** [comment]
Just checking back to see if you had any updates on the issue?

**Comment by bugsounet** [comment]
updated to v1.5.0

**Comment by bugsounet** [comment]
and updated to v1.5.1 for correct a token creation
