### ISSUE TITLE
Touch button

### ISSUE THREAD

**Issue by Val0l** [skuethe/MMM-Spotify#97]
Hello,

I managed to install this module. It's all working. But I want to make a tactile mirror. How do I get the buttons to react as soon as I touch them (pause/resume/next/...)? Thanks.

**Comment by bugsounet** [comment]
Hi, this feature is already supported but needed a premium account

**Comment by Val0l** [comment]
Hello I just need a premium account and it's going to go straight to touch?

**Comment by bugsounet** [comment]
sure, just press wanted icon

**Comment by Val0l** [comment]
Okay, thank you so much for your help.
