### ISSUE TITLE
sportify not working 

### ISSUE THREAD

**Issue by ahmadmutzakhisyah** [skuethe/MMM-Spotify#98]
haii I have a problem that the MMM-Sportify module can't play music or is called by google assistant, how is the solution
I have my following config.js

 spotify: {
      useSpotify: true,
      useIntegred: true, // !!! DEV !!!
      useLibrespot: true, // !!! DEV !!!
      connectTo: null,
      playDelay: 3000,
      minVolume: 10,
      maxVolume: 100,
      updateInterval: 1000, // !!! DEV !!!
      idleInterval: 10000, // !!! DEV !!!
      TOKEN: "./SmartMirror-token.json", // !!! DEV !!!
      CLIENT_ID: "f8d ******", // !!! DEV !!!
      CLIENT_SECRET: "7b125ff6429f4b019 **********", // !!! DEV !!!
      deviceDisplay: "Listening on", // !!! DEV !!!
    },

{
  module: "MMM-Spotify",
  position: "bottom_left", // "bottom_bar" or "top_bar" for miniBar
  config: {
    debug: false, // debug mode
    style: "mini", // "default" or "mini" available (inactive for miniBar)
    control: "hidden",
    accountDefault: 0, // default account number, attention: 0 is the first account
    updateInterval: 1000, // update interval when playing
    idleInterval: 30000, // update interval on idle
    onStart: null, // disable the onStart feature with `null`
    deviceDisplay: "Listening on", // text to display in the device block (default style only)
    allowDevices: [], // If you want to limit devices to display info, use this.
    // allowDevices: ["RASPOTIFY", "My iPhoneX", "My Home speaker"],
    miniBarConfig: {
      album: true, // display Album name in miniBar style
      scroll: true, // scroll title / artist / album in miniBar style
      logo: true, // display Spotify logo in miniBar style
    }
  }
},

**Comment by bugsounet** [comment]
MMM-Spotify don't play any music
It can just display visual informations

**Comment by ahmadmutzakhisyah** [comment]
okey thank for your help
