### ISSUE TITLE
Change device for volume ...

### ISSUE THREAD

**Issue by jamesvcc** [skuethe/MMM-Spotify#99]
Using the "default" style for displaying a large Spotify information panel I would like to replace the line of text "Listening on xxxxxxx" to show the current volume instead (either as a value or a small 0-100 progress bar would be fantastic) - how would I go about this as I am a beginner and do not know where to start.

Thanks for your help.

**Comment by bugsounet** [comment]
Hi, I planned to do this in the default ui (like bottom_bar ui)
It's complex to explain, needed a couple of CSS and JS code

**Comment by jamesvcc** [comment]
Oh, OK so I guess I can wait and you will get to it at some point?

**Comment by bugsounet** [comment]
It's not difficult for me ;)
I just have to take the time to do it ! :)
and unfortunately I don't have just one module

**Comment by jamesvcc** [comment]
I understand.  Thanks for coming back to me and I am happy to wait.  The module is excellent, I just wish I could customise it more myself but I do not have the knowledge.

**Comment by bugsounet** [comment]
So, just wait and see ;)

**Comment by jamesvcc** [comment]
Another amazing enhancement if it is possible is in the iOS Spotify client for some tracks it will show short video clips instead of album artwork.  It would be wonderful if it was possible to show these as an option.

**Comment by skuethe** [comment]
@jamesvcc : device volume is now shown by default. See current screenshot:
https://github.com/skuethe/MMM-Spotify/blob/master/screenshots/spotify_default.png

**Comment by skuethe** [comment]
> 
> 
> Another amazing enhancement if it is possible is in the iOS Spotify client for some tracks it will show short video clips instead of album artwork. It would be wonderful if it was possible to show these as an option.

A quick search didn't really bring anything up. So it seems this is some special function for mobile apps? Feel free to update this if you find anything on that subject, but I think this is currently not possible.
